In [82]:
!pip3 install numpy


[notice] A new release of pip is available: 24.0 -> 24.3.1
[notice] To update, run: C:\Users\kmura\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


### Basic Operations

In [83]:
import numpy as np

In [84]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [85]:
print(a[0])

1


In [86]:
import time
import sys

In [87]:
b =range(1000)
print(sys.getsizeof(5)*len(b))

28000


In [88]:
c =np.arange(1000)
print(c.size*c.itemsize)

8000


In [89]:
size = 1000000


In [90]:
l1 = range(size)
l2 = range(size)
A1 = np.arange(size)
A2 = np.arange(size)


In [91]:
start = time.time()
result = [(x+y) for x,y in zip(l1,l2)]
print((time.time()-start)*1000)

106.32038116455078


In [92]:
start = time.time()
result = A1 + A2
print((time.time()-start)*1000)

16.273975372314453


In [93]:
a = np.array([[1,2],[3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [94]:
a.ndim 

2

In [95]:
a.itemsize

8

In [96]:
a.shape
# important in data science

(3, 2)

In [97]:
a = np.array([[1,2],[3,4],[5,6]], dtype = np.float64)
a

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [98]:
a.itemsize

8

In [99]:
a.size,a.shape

(6, (3, 2))

In [100]:
a = np.array([[1,2],[3,4],[5,6]], dtype = np.complex64)
print(a)

[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]
 [5.+0.j 6.+0.j]]


In [101]:
a = np.ones((3,4))
print(a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [102]:
q = range(4)
q

range(0, 4)

In [103]:
l = np.arange(5)
l

array([0, 1, 2, 3, 4])

In [104]:
print(np.char.add(['hello','hi'],['abc','xyz']))

['helloabc' 'hixyz']


In [105]:
print(np.char.multiply('Hello',3))

HelloHelloHello


In [106]:
print(np.char.capitalize('hello'))
print(np.char.title('hello how are you?'))


Hello
Hello How Are You?


In [107]:
print(np.char.lower(['HELLO','WORLD']))
print(np.char.lower('HELLO'))

['hello' 'world']
hello


In [108]:
print(np.char.split('hello how are you?'))

['hello', 'how', 'are', 'you?']


In [109]:
print(np.char.splitlines('hello\nhow are you?'))

['hello', 'how are you?']


In [110]:
print(np.char.split('hello how are you?',' '))

['hello', 'how', 'are', 'you?']


In [111]:
print(np.char.strip(['arora','admin','java'],'a'))

['ror' 'dmin' 'jav']


In [112]:
print(np.char.join(':','dmy'))

d:m:y


In [113]:
print(np.char.replace("how are you","are","is"))

how is you


### Coding Stuff

In [114]:
# Array manipualtion
import numpy as np

In [115]:
a = np.arange(0,8)
print(a)
b = a.reshape(2,4)
print(b)

[0 1 2 3 4 5 6 7]
[[0 1 2 3]
 [4 5 6 7]]


In [116]:
print(b.flatten())

[0 1 2 3 4 5 6 7]


In [117]:
print(b.flatten(order = 'F')) #A?C?F available A and C are default

[0 4 1 5 2 6 3 7]


In [118]:
a = np.arange(12).reshape(4,3)
print(a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [119]:
print(np.transpose(a))

[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


In [120]:
b = np.arange(8).reshape(2,4)
print(b)
print(np.transpose(b))

[[0 1 2 3]
 [4 5 6 7]]
[[0 4]
 [1 5]
 [2 6]
 [3 7]]


In [121]:
c = b.reshape(2,2,2)
print(c)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [122]:
np.rollaxis(c,2,1)

array([[[0, 2],
        [1, 3]],

       [[4, 6],
        [5, 7]]])

In [123]:
a =np.arange(8).reshape(2,4)
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [124]:
b = np.array([8,9,10,11]).reshape(1,4)
b

array([[ 8,  9, 10, 11]])

In [125]:
np.add(a,b)

array([[ 8, 10, 12, 14],
       [12, 14, 16, 18]])

In [126]:
np.multiply(a,b)

array([[ 0,  9, 20, 33],
       [32, 45, 60, 77]])

In [127]:
np.divide(a,b)

array([[0.        , 0.11111111, 0.2       , 0.27272727],
       [0.5       , 0.55555556, 0.6       , 0.63636364]])

In [ ]:
#Slicing
